version: "3.1"
services:
  mysql:
    container_name: mysql-watch # container name
    image: mysql:5.7 # images version
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"
  app-pm2:
    container_name: app-pm2
    build: .
    # volumes:
    # - /wwwroot/watch:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
