version: "3.1"
services:
  mysql:
    container_name: watch2-mysql # container name
    image: mysql:5.7 # images version
    ports:
      - "3308:3306"
    env_file:
    - ./.env
    # environment:
    volumes:
        - "${MYSQL_DIR}/data:/var/lib/mysql"           # data
        - "${MYSQL_DIR}/config:/etc/mysql/conf.d"      # config
  app-pm2:
    container_name: pm2-watch
    build: .
    volumes:
      - /etc/localtime:/etc/localtime
    # - /wwwroot/watch:/usr/src/app
    ports:
      - "3001:3000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
